{"uuid":"6eb13383-ade0-44d9-89ad-3e0d561468fa","historyId":"c59643030e1e776644fd5d1d6aa79cfc","status":"failed","statusDetails":{"message":"The following error originated from your test code, not from Cypress.\n\n  > given is not defined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","trace":"ReferenceError: The following error originated from your test code, not from Cypress.\n\n  > given is not defined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at Object.1 (http://localhost:64430/__cypress/tests?p=cypress\\integration\\cucumber\\allure\\steps.js:4:1)\n    at o (http://localhost:64430/__cypress/tests?p=cypress\\integration\\cucumber\\allure\\steps.js:1:265)\n    at r (http://localhost:64430/__cypress/tests?p=cypress\\integration\\cucumber\\allure\\steps.js:1:431)\n    at eval (http://localhost:64430/__cypress/tests?p=cypress\\integration\\cucumber\\allure\\steps.js:1:460)\n    at eval (<anonymous>)"},"stage":"finished","steps":[],"attachments":[{"name":"cucumber/allure/steps.js:2022-03-03T22:00:31.253Z","type":"image/png","source":"48028e7b-89a8-4cd6-9326-8ecf730b05d0-attachment.png"},{"name":"video recording","type":"video/mp4","source":"6d4d8561-9a7c-49b8-846b-6ac3a1db3694-attachment.mp4"}],"parameters":[],"labels":[],"links":[],"start":1646344831231,"name":"An uncaught error was detected outside of a test","fullName":"An uncaught error was detected outside of a test","stop":1646344831629}